name: PHASCIA
favicon: null
layout_spectrum: 0.75421
typography_spectrum: 0.60268
title: 'PHASCIA '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f3f5e8'
    - '#f7ee00'
    - '#536770'
    - '#00bd01'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
