name: PHASCIA
favicon: null
layout_spectrum: 0.75421
typography_spectrum: 0.60268
title: 'PHASCIA '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fdfffa'
    - '#00fefe'
    - '#0275fa'
    - '#0031f6'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
