name: PHASCIA
favicon: null
layout_spectrum: 0.69024
typography_spectrum: 0.60773
title: 'PHASCIA '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#6cc1d5'
    - '#d1e7e6'
    - '#333328'
    - '#237081'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
