name: PHASCIA
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60605
title: 'PHASCIA '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#140c0c'
    - '#495f90'
    - '#f6f87b'
    - '#f7c15d'
    - '#abaeb7'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
