name: PHASCIA
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60605
title: 'PHASCIA '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f0a0e'
    - '#c097d2'
    - '#907087'
    - '#7277eb'
    - '#2a3d9a'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
