name: PHASCIA
favicon: null
layout_spectrum: 0.75421
typography_spectrum: 0.60268
title: 'PHASCIA '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fffed8'
    - '#4c4348'
    - '#ff00a9'
    - '#73ca93'
  brandStrength: 0.25
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
